/* Copyright (c) 2026 multiarch-scala contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * Build-time generator for the Scala.js half of the shared resource-access mechanism.
 *
 * `Class.getResourceAsStream` is unavailable on Scala.js, so the JS build embeds a resource
 * directory directly into the compiled output. This generator walks a resource directory and emits
 * a Scala object whose initializer registers every file's bytes into
 * `multiarch.resources.EmbeddedResources` (keyed by the classpath-absolute resource path, e.g.
 * "/data/table.csv"). The runtime Scala.js `PlatformResourcesImpl` consults that registry first.
 *
 * Resource bytes are Base64-encoded (ASCII) and split into multiple string literals to stay well
 * under the JVM 64KB string-constant (UTF-8 byte) limit. The chunks are concatenated and
 * Base64-decoded lazily on first access, so unused resources cost nothing at object initialization.
 *
 * Ported from SSG's project/EmbeddedResourcesGen.scala, generalized into a reusable plugin task. */
package multiarch.sbt

import sbt._

import java.io.File
import java.nio.file.Files
import java.util.Base64

object EmbeddedResourcesGen {

  // Base64 is pure ASCII, so character count equals UTF-8 byte count. 40000 keeps each string
  // literal comfortably below the 65535-byte classfile constant-pool limit.
  private val ChunkSize: Int = 40000

  /** Walks `resourceDir` and writes a Scala object embedding every file's bytes into `outFile`.
    *
    * @param resourceDir
    *   directory whose files become embedded resources (recursively)
    * @param outFile
    *   target Scala source file (typically under `sourceManaged`)
    * @param objectName
    *   fully-qualified name of the generated object, e.g. "multiarch.resources.GeneratedEmbeddedResources"
    * @param log
    *   sbt logger
    * @return
    *   the generated file (so it can be returned from a `sourceGenerators` task)
    */
  def generate(resourceDir: File, outFile: File, objectName: String, log: sbt.util.Logger): File = {
    val files: Seq[File] =
      if (resourceDir.isDirectory) {
        (resourceDir ** "*").get().filter(_.isFile).sortBy(_.getPath)
      } else {
        Seq.empty
      }

    val (pkg, simpleName) = splitName(objectName)

    val sb = new StringBuilder

    sb.append("/* Copyright (c) 2026 multiarch-scala contributors\n")
    sb.append(" * SPDX-License-Identifier: Apache-2.0\n")
    sb.append(" *\n")
    sb.append(" * GENERATED by multiarch.sbt.EmbeddedResourcesGen — do not edit by hand.\n")
    sb.append(" * Embeds a resource directory for the Scala.js platform so resource lookup does not\n")
    sb.append(" * depend on the process working directory. */\n")
    if (pkg.nonEmpty) {
      sb.append("package ").append(pkg).append("\n\n")
    }
    sb.append("import java.util.Base64\n\n")
    sb.append("import multiarch.resources.EmbeddedResources\n\n")
    sb.append("object ").append(simpleName).append(" {\n\n")

    val entries = files.zipWithIndex.map { case (file, idx) =>
      val rel     = resourceDir.toPath.relativize(file.toPath).toString.replace('\\', '/')
      val path    = "/" + rel
      val bytes   = Files.readAllBytes(file.toPath)
      val encoded = Base64.getEncoder.encodeToString(bytes)
      val name    = "res" + idx

      sb.append("  private def ").append(name).append("(): Array[Byte] = {\n")
      sb.append("    val b = new StringBuilder\n")
      var off = 0
      while (off < encoded.length) {
        val end   = math.min(off + ChunkSize, encoded.length)
        val chunk = encoded.substring(off, end)
        sb.append("    b.append(\"").append(chunk).append("\")\n")
        off = end
      }
      if (encoded.isEmpty) {
        sb.append("    val _ = b // empty resource\n")
      }
      sb.append("    Base64.getDecoder.decode(b.toString)\n")
      sb.append("  }\n\n")

      (path, name)
    }

    sb.append("  /** Classpath-absolute resource path -> thunk producing freshly-decoded bytes. */\n")
    sb.append("  val resources: Map[String, () => Array[Byte]] = Map(\n")
    entries.zipWithIndex.foreach { case ((path, name), i) =>
      sb.append("    \"").append(escape(path)).append("\" -> (() => ").append(name).append("())")
      if (i < entries.length - 1) {
        sb.append(",")
      }
      sb.append("\n")
    }
    sb.append("  )\n\n")
    sb.append("  // Register with the shared runtime registry at object initialization.\n")
    sb.append("  EmbeddedResources.register(resources)\n")
    sb.append("}\n")

    Files.createDirectories(outFile.toPath.getParent)
    IO.write(outFile, sb.toString)
    log.info(s"[multiarch-resources] embedded ${entries.length} resource(s) into ${outFile.getName} ($objectName)")
    outFile
  }

  private def splitName(fqcn: String): (String, String) = {
    val idx = fqcn.lastIndexOf('.')
    if (idx < 0) ("", fqcn)
    else (fqcn.substring(0, idx), fqcn.substring(idx + 1))
  }

  private def escape(s: String): String =
    s.flatMap {
      case '\\' => "\\\\"
      case '"'  => "\\\""
      case c    => c.toString
    }
}
